services:
  db:
    build:
      context: .
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: samplepassword
    ports:
      - "5432:5432"
    volumes:
      - db-vol:/var/lib/postgresql/data

  django:
    build: ./backend/.
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: samplepassword
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-vol: